# Generated by Django 4.2.11 on 2026-05-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('common_elements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
