# Generated by Django 4.2.11 on 2026-05-30 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('developer', '0001_initial'),
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('consoles', models.ManyToManyField(related_name='games', to='console.console')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='developer.developer')),
                ('genre', models.ManyToManyField(related_name='games', to='genre.genre')),
            ],
            options={
                'db_table': 'catalog_game',
            },
        ),
    ]
