# Generated by Django 4.2.11 on 2026-05-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_screenshot'),
        ('catalog', '0005_screenshot_review'),
    ]

    operations = [
    ]
